from pxr import Sdf, Usd, Plug
import os
import pytest


# Ensure the plugin is loaded
def setup_module(module):
    plugin = Plug.Registry().GetPluginWithName("parquetFormat")
    if plugin and not plugin.isLoaded:
        plugin.Load()


def test_properties_missing_in_usda():
    """
    Test that properties do not exist on the USDA layer by itself.
    """
    # Create a simple USDA layer
    layer = Sdf.Layer.CreateAnonymous(".usda")
    layer.ImportFromString("""#usda 1.0
def "World" {
    def "Sphere1" {
    }
}
""")

    stage = Usd.Stage.Open(layer)
    prim = stage.GetPrimAtPath("/World/Sphere1")
    assert prim.IsValid()

    # Assert 'temperature' attribute does not exist
    temp_attr = prim.GetAttribute("temperature")
    assert not temp_attr.IsValid()


def test_properties_present_with_parquet_sublayer():
    """
    Test that properties are added when we reference in the parquet sublayer.
    """
    # Ensure test data exists (it should be created by create_test_parquet.py or similar)
    # For this test, we can use the small test file generated by create_test_parquet.py
    # or generate a temporary one. Let's rely on 'tests/data/test_data.parquet'
    # which is used in existing tests.

    parquet_file = os.path.abspath("tests/data/test_data.parquet")
    if not os.path.exists(parquet_file):
        # Fallback: create it if it doesn't exist for some reason,
        # though it should strictly be there from setup.
        # But to be safe in this isolated test execution:
        import pandas as pd
        import pyarrow as pa
        import pyarrow.parquet as pq

        data = {"path": ["/World/Sphere1"], "temperature": [25.5]}
        df = pd.DataFrame(data)
        os.makedirs(os.path.dirname(parquet_file), exist_ok=True)
        table = pa.Table.from_pandas(df)
        pq.write_table(table, parquet_file)

    # Create a USDA layer that sublayers the parquet file
    layer = Sdf.Layer.CreateAnonymous(".usda")
    layer.ImportFromString("""#usda 1.0
def "World" {
    def "Sphere1" {
    }
}
""")

    # Add parquet sublayer
    # Note: Parquet file needs to be in a place where USD can find it, or absolute path.
    # We'll use absolute path for certainty.
    layer.subLayerPaths.append(parquet_file)

    stage = Usd.Stage.Open(layer)
    prim = stage.GetPrimAtPath("/World/Sphere1")
    assert prim.IsValid()

    # Assert 'temperature' attribute NOW exists and has correct value
    temp_attr = prim.GetAttribute("temperature")
    assert temp_attr.IsValid()
    assert temp_attr.Get() == 25.5
